################################################################################
# How to create a tag to build a proper release (tag will get integrated into build)
# git tag -a "0.1.0" -m "Release v0.1.0"
# git push origin --tags
################################################################################
# WARNING: Make sure to set action permissions to max ("Read and write permissions")
name: Build/Release
on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  synthesis:
    runs-on: ubuntu-latest

    steps:
      - name: "üß∞ Checkout Repository"
        uses: actions/checkout@v4

      - name: "üß∞ Checkout Packybara"
        uses: actions/checkout@v4
        with:
          repository: "agg23/pocketpublish"
          path: ".github/publish"

      - name: "üèóÔ∏è Compile design"
        shell: bash
        run: |
          cmd="docker run --rm -v ${{ github.workspace }}:/build raetro/quartus:21.1 quartus_sh --flow compile projects/nes_pocket.qpf"
          echo "Running command: $cmd"
          eval $cmd

      - name: Upload failure artifact
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failure_output_files
          path: projects/output_files/

      - name: Reverse bitstream
        shell: bash
        run: |
          mkdir artifacts
          pip3 install -r .github/publish/requirements.txt
          python3 .github/publish/reverse.py projects/output_files/nes_pocket.rbf artifacts/nes.rev

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nes
          path: artifacts/nes.rev

  packaging:
    runs-on: ubuntu-latest
    needs: synthesis
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "üß∞ Checkout Repository"
        uses: actions/checkout@v4

      - name: "üß∞ Checkout Packybara"
        uses: actions/checkout@v4
        with:
          repository: "agg23/pocketpublish"
          path: ".github/publish"

      - name: "Create folders"
        run: |
          pip3 install -r .github/publish/requirements.txt
          python3 .github/publish/create_folders.py

      - name: "Download artifacts"
        uses: actions/download-artifact@v4
        with:
          path: staging/Cores/agg23.NES/
          merge-multiple: true

      - name: "Release"
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            python3 .github/publish/release.py --norelease
          else
            python3 .github/publish/release.py
          fi

      - name: "Upload Actions artifact"
        uses: actions/upload-artifact@v4
        with:
          path: release/*.zip
